version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202008-01
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Setup nvim ppa
          command: sudo add-apt-repository --yes ppa:neovim-ppa/unstable
      - run:
          name: APT update
          command: sudo apt-get update
      - run:
          name: Install dependencies
          command: |
            sudo apt-get install -y cmake libqt5svg5 libqt5svg5-dev neovim python3-dev python3-jinja2 python3-msgpack python3-pip qt5-default
            sudo apt-get install -y lcov
      - run:
          name: build
          command: |
            pyenv global system
            mkdir build
            cd build
            cmake -DCMAKE_BUILD_TYPE=Debug -DUSE_GCOV=ON -DPYTHON_EXECUTABLE=/usr/bin/python3 -DENABLE_TESTS=ON ..
            cmake --build . --target bindings -- VERBOSE=1
            cmake --build . -- VERBOSE=1
      - run:
          name: test
          command: |
            cd build
            ctest -VV
      - run:
          name: Generate coverage report with lcov
          command: lcov --directory . --capture --output-file coverage.info
      - run:
          name: Upload coverage report to codecov
          command: bash <(curl -s https://codecov.io/bash) -f coverage.info 
      - store_test_results:
          path: build/test_shellwidget_output/
